"""add phase 6 evidence paper pipeline

Revision ID: 20260828_0007
Revises: 20260828_0006
Create Date: 2026-08-28 22:16:23.441239
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260828_0007"
down_revision: str | None = "20260828_0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "literature_references",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("reference_id", sa.String(length=100), nullable=False),
        sa.Column("doi", sa.String(length=255), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("metadata_status", sa.String(length=32), nullable=False),
        sa.Column(
            "reference_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_literature_references_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_literature_references")),
        sa.UniqueConstraint("project_id", "reference_id", name="uq_references_project_ref"),
    )
    op.create_index(
        op.f("ix_literature_references_doi"), "literature_references", ["doi"], unique=False
    )
    op.create_index(
        op.f("ix_literature_references_metadata_status"),
        "literature_references",
        ["metadata_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_literature_references_project_id"),
        "literature_references",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_literature_references_reference_id"),
        "literature_references",
        ["reference_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_literature_references_source"), "literature_references", ["source"], unique=False
    )
    op.create_index(
        op.f("ix_literature_references_source_id"),
        "literature_references",
        ["source_id"],
        unique=False,
    )
    op.create_table(
        "paper_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("paper_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("problem_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("parent_version", sa.Integer(), nullable=True),
        sa.Column("verified_result_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("manifest_hash", sa.String(length=64), nullable=True),
        sa.Column("paper_agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("paper_agent_is_mock", sa.Boolean(), nullable=False),
        sa.Column(
            "version_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "quality_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "compile_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["problems.id"],
            name=op.f("fk_paper_versions_problem_id_problems"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_paper_versions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["verified_result_id"],
            ["results.id"],
            name=op.f("fk_paper_versions_verified_result_id_results"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paper_versions")),
        sa.UniqueConstraint("paper_id", "version", name="uq_paper_versions_paper_version"),
    )
    op.create_index(
        op.f("ix_paper_versions_evidence_snapshot_hash"),
        "paper_versions",
        ["evidence_snapshot_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_versions_evidence_snapshot_id"),
        "paper_versions",
        ["evidence_snapshot_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_paper_versions_manifest_hash"), "paper_versions", ["manifest_hash"], unique=False
    )
    op.create_index(
        op.f("ix_paper_versions_paper_agent_run_id"),
        "paper_versions",
        ["paper_agent_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_versions_paper_id"), "paper_versions", ["paper_id"], unique=False
    )
    op.create_index(
        op.f("ix_paper_versions_problem_id"), "paper_versions", ["problem_id"], unique=False
    )
    op.create_index(
        op.f("ix_paper_versions_project_id"), "paper_versions", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_paper_versions_status"), "paper_versions", ["status"], unique=False)
    op.create_index(
        op.f("ix_paper_versions_verified_result_id"),
        "paper_versions",
        ["verified_result_id"],
        unique=False,
    )
    op.create_table(
        "citation_support_checks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("paper_version_record_id", sa.Uuid(), nullable=False),
        sa.Column("claim_id", sa.String(length=100), nullable=False),
        sa.Column("reference_id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("reviewer_is_mock", sa.Boolean(), nullable=False),
        sa.Column(
            "check_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_version_record_id"],
            ["paper_versions.id"],
            name=op.f("fk_citation_support_checks_paper_version_record_id_paper_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_citation_support_checks_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_citation_support_checks")),
    )
    op.create_index(
        op.f("ix_citation_support_checks_claim_id"),
        "citation_support_checks",
        ["claim_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_citation_support_checks_paper_version_record_id"),
        "citation_support_checks",
        ["paper_version_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_citation_support_checks_project_id"),
        "citation_support_checks",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_citation_support_checks_reference_id"),
        "citation_support_checks",
        ["reference_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_citation_support_checks_reviewer_is_mock"),
        "citation_support_checks",
        ["reviewer_is_mock"],
        unique=False,
    )
    op.create_index(
        op.f("ix_citation_support_checks_status"),
        "citation_support_checks",
        ["status"],
        unique=False,
    )
    op.create_table(
        "claims",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("paper_version_record_id", sa.Uuid(), nullable=False),
        sa.Column("claim_id", sa.String(length=100), nullable=False),
        sa.Column("claim_type", sa.String(length=32), nullable=False),
        sa.Column("importance", sa.String(length=16), nullable=False),
        sa.Column("verification_status", sa.String(length=32), nullable=False),
        sa.Column(
            "claim_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_version_record_id"],
            ["paper_versions.id"],
            name=op.f("fk_claims_paper_version_record_id_paper_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_claims_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claims")),
        sa.UniqueConstraint("paper_version_record_id", "claim_id", name="uq_claims_paper_claim"),
    )
    op.create_index(op.f("ix_claims_claim_id"), "claims", ["claim_id"], unique=False)
    op.create_index(op.f("ix_claims_claim_type"), "claims", ["claim_type"], unique=False)
    op.create_index(op.f("ix_claims_importance"), "claims", ["importance"], unique=False)
    op.create_index(
        op.f("ix_claims_paper_version_record_id"),
        "claims",
        ["paper_version_record_id"],
        unique=False,
    )
    op.create_index(op.f("ix_claims_project_id"), "claims", ["project_id"], unique=False)
    op.create_index(
        op.f("ix_claims_verification_status"), "claims", ["verification_status"], unique=False
    )
    op.create_table(
        "document_registry",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("paper_version_record_id", sa.Uuid(), nullable=False),
        sa.Column("object_id", sa.String(length=100), nullable=False),
        sa.Column("object_type", sa.String(length=32), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "entry_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_version_record_id"],
            ["paper_versions.id"],
            name=op.f("fk_document_registry_paper_version_record_id_paper_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_registry")),
    )
    op.create_index(
        op.f("ix_document_registry_content_hash"),
        "document_registry",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_registry_object_id"), "document_registry", ["object_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_registry_object_type"), "document_registry", ["object_type"], unique=False
    )
    op.create_index(
        op.f("ix_document_registry_paper_version_record_id"),
        "document_registry",
        ["paper_version_record_id"],
        unique=False,
    )
    op.create_table(
        "evidence_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("problem_id", sa.Uuid(), nullable=False),
        sa.Column("paper_version_record_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_type", sa.String(length=40), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("source_version", sa.String(length=100), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("verification_status", sa.String(length=32), nullable=False),
        sa.Column(
            "record_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["paper_version_record_id"],
            ["paper_versions.id"],
            name=op.f("fk_evidence_records_paper_version_record_id_paper_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["problems.id"],
            name=op.f("fk_evidence_records_problem_id_problems"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_evidence_records_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_records")),
    )
    op.create_index(
        op.f("ix_evidence_records_evidence_type"),
        "evidence_records",
        ["evidence_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_records_paper_version_record_id"),
        "evidence_records",
        ["paper_version_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_records_problem_id"), "evidence_records", ["problem_id"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_records_project_id"), "evidence_records", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_records_source_hash"), "evidence_records", ["source_hash"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_records_source_id"), "evidence_records", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_records_source_type"), "evidence_records", ["source_type"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_records_verification_status"),
        "evidence_records",
        ["verification_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_records_verified"), "evidence_records", ["verified"], unique=False
    )
    op.create_table(
        "figures",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("paper_version_record_id", sa.Uuid(), nullable=False),
        sa.Column("figure_id", sa.String(length=100), nullable=False),
        sa.Column("data_hash", sa.String(length=64), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("image_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "figure_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_version_record_id"],
            ["paper_versions.id"],
            name=op.f("fk_figures_paper_version_record_id_paper_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_figures_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_figures")),
    )
    op.create_index(op.f("ix_figures_code_hash"), "figures", ["code_hash"], unique=False)
    op.create_index(op.f("ix_figures_data_hash"), "figures", ["data_hash"], unique=False)
    op.create_index(op.f("ix_figures_figure_id"), "figures", ["figure_id"], unique=False)
    op.create_index(op.f("ix_figures_image_hash"), "figures", ["image_hash"], unique=False)
    op.create_index(
        op.f("ix_figures_paper_version_record_id"),
        "figures",
        ["paper_version_record_id"],
        unique=False,
    )
    op.create_index(op.f("ix_figures_project_id"), "figures", ["project_id"], unique=False)
    op.create_table(
        "literature_searches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("problem_id", sa.Uuid(), nullable=False),
        sa.Column("paper_version_record_id", sa.Uuid(), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "plan_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_version_record_id"],
            ["paper_versions.id"],
            name=op.f("fk_literature_searches_paper_version_record_id_paper_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["problems.id"],
            name=op.f("fk_literature_searches_problem_id_problems"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_literature_searches_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_literature_searches")),
    )
    op.create_index(
        op.f("ix_literature_searches_paper_version_record_id"),
        "literature_searches",
        ["paper_version_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_literature_searches_problem_id"),
        "literature_searches",
        ["problem_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_literature_searches_project_id"),
        "literature_searches",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_literature_searches_source"), "literature_searches", ["source"], unique=False
    )
    op.create_index(
        op.f("ix_literature_searches_status"), "literature_searches", ["status"], unique=False
    )
    op.create_table(
        "paper_artifacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("paper_version_record_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=1024), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["paper_version_record_id"],
            ["paper_versions.id"],
            name=op.f("fk_paper_artifacts_paper_version_record_id_paper_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_paper_artifacts_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paper_artifacts")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_paper_artifacts_storage_key")),
    )
    op.create_index(op.f("ix_paper_artifacts_kind"), "paper_artifacts", ["kind"], unique=False)
    op.create_index(
        op.f("ix_paper_artifacts_paper_version_record_id"),
        "paper_artifacts",
        ["paper_version_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_artifacts_project_id"), "paper_artifacts", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_paper_artifacts_sha256"), "paper_artifacts", ["sha256"], unique=False)
    op.create_table(
        "paper_sections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("paper_version_record_id", sa.Uuid(), nullable=False),
        sa.Column("section_id", sa.String(length=100), nullable=False),
        sa.Column("section_type", sa.String(length=40), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column(
            "section_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_version_record_id"],
            ["paper_versions.id"],
            name=op.f("fk_paper_sections_paper_version_record_id_paper_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paper_sections")),
    )
    op.create_index(
        op.f("ix_paper_sections_paper_version_record_id"),
        "paper_sections",
        ["paper_version_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_sections_section_id"), "paper_sections", ["section_id"], unique=False
    )
    op.create_index(
        op.f("ix_paper_sections_section_type"), "paper_sections", ["section_type"], unique=False
    )
    op.create_table(
        "tables",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("paper_version_record_id", sa.Uuid(), nullable=False),
        sa.Column("table_id", sa.String(length=100), nullable=False),
        sa.Column("data_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "table_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_version_record_id"],
            ["paper_versions.id"],
            name=op.f("fk_tables_paper_version_record_id_paper_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_tables_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tables")),
    )
    op.create_index(op.f("ix_tables_data_hash"), "tables", ["data_hash"], unique=False)
    op.create_index(
        op.f("ix_tables_paper_version_record_id"),
        "tables",
        ["paper_version_record_id"],
        unique=False,
    )
    op.create_index(op.f("ix_tables_project_id"), "tables", ["project_id"], unique=False)
    op.create_index(op.f("ix_tables_table_id"), "tables", ["table_id"], unique=False)
    op.create_table(
        "claim_evidence_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("claim_record_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_record_id", sa.Uuid(), nullable=False),
        sa.Column("support", sa.String(length=32), nullable=False),
        sa.Column("source_field", sa.String(length=255), nullable=True),
        sa.Column(
            "link_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["claim_record_id"],
            ["claims.id"],
            name=op.f("fk_claim_evidence_links_claim_record_id_claims"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_record_id"],
            ["evidence_records.id"],
            name=op.f("fk_claim_evidence_links_evidence_record_id_evidence_records"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_claim_evidence_links_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claim_evidence_links")),
    )
    op.create_index(
        op.f("ix_claim_evidence_links_claim_record_id"),
        "claim_evidence_links",
        ["claim_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_claim_evidence_links_evidence_record_id"),
        "claim_evidence_links",
        ["evidence_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_claim_evidence_links_project_id"),
        "claim_evidence_links",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_claim_evidence_links_support"), "claim_evidence_links", ["support"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_claim_evidence_links_support"), table_name="claim_evidence_links")
    op.drop_index(op.f("ix_claim_evidence_links_project_id"), table_name="claim_evidence_links")
    op.drop_index(
        op.f("ix_claim_evidence_links_evidence_record_id"), table_name="claim_evidence_links"
    )
    op.drop_index(
        op.f("ix_claim_evidence_links_claim_record_id"), table_name="claim_evidence_links"
    )
    op.drop_table("claim_evidence_links")
    op.drop_index(op.f("ix_tables_table_id"), table_name="tables")
    op.drop_index(op.f("ix_tables_project_id"), table_name="tables")
    op.drop_index(op.f("ix_tables_paper_version_record_id"), table_name="tables")
    op.drop_index(op.f("ix_tables_data_hash"), table_name="tables")
    op.drop_table("tables")
    op.drop_index(op.f("ix_paper_sections_section_type"), table_name="paper_sections")
    op.drop_index(op.f("ix_paper_sections_section_id"), table_name="paper_sections")
    op.drop_index(op.f("ix_paper_sections_paper_version_record_id"), table_name="paper_sections")
    op.drop_table("paper_sections")
    op.drop_index(op.f("ix_paper_artifacts_sha256"), table_name="paper_artifacts")
    op.drop_index(op.f("ix_paper_artifacts_project_id"), table_name="paper_artifacts")
    op.drop_index(op.f("ix_paper_artifacts_paper_version_record_id"), table_name="paper_artifacts")
    op.drop_index(op.f("ix_paper_artifacts_kind"), table_name="paper_artifacts")
    op.drop_table("paper_artifacts")
    op.drop_index(op.f("ix_literature_searches_status"), table_name="literature_searches")
    op.drop_index(op.f("ix_literature_searches_source"), table_name="literature_searches")
    op.drop_index(op.f("ix_literature_searches_project_id"), table_name="literature_searches")
    op.drop_index(op.f("ix_literature_searches_problem_id"), table_name="literature_searches")
    op.drop_index(
        op.f("ix_literature_searches_paper_version_record_id"), table_name="literature_searches"
    )
    op.drop_table("literature_searches")
    op.drop_index(op.f("ix_figures_project_id"), table_name="figures")
    op.drop_index(op.f("ix_figures_paper_version_record_id"), table_name="figures")
    op.drop_index(op.f("ix_figures_image_hash"), table_name="figures")
    op.drop_index(op.f("ix_figures_figure_id"), table_name="figures")
    op.drop_index(op.f("ix_figures_data_hash"), table_name="figures")
    op.drop_index(op.f("ix_figures_code_hash"), table_name="figures")
    op.drop_table("figures")
    op.drop_index(op.f("ix_evidence_records_verified"), table_name="evidence_records")
    op.drop_index(op.f("ix_evidence_records_verification_status"), table_name="evidence_records")
    op.drop_index(op.f("ix_evidence_records_source_type"), table_name="evidence_records")
    op.drop_index(op.f("ix_evidence_records_source_id"), table_name="evidence_records")
    op.drop_index(op.f("ix_evidence_records_source_hash"), table_name="evidence_records")
    op.drop_index(op.f("ix_evidence_records_project_id"), table_name="evidence_records")
    op.drop_index(op.f("ix_evidence_records_problem_id"), table_name="evidence_records")
    op.drop_index(
        op.f("ix_evidence_records_paper_version_record_id"), table_name="evidence_records"
    )
    op.drop_index(op.f("ix_evidence_records_evidence_type"), table_name="evidence_records")
    op.drop_table("evidence_records")
    op.drop_index(
        op.f("ix_document_registry_paper_version_record_id"), table_name="document_registry"
    )
    op.drop_index(op.f("ix_document_registry_object_type"), table_name="document_registry")
    op.drop_index(op.f("ix_document_registry_object_id"), table_name="document_registry")
    op.drop_index(op.f("ix_document_registry_content_hash"), table_name="document_registry")
    op.drop_table("document_registry")
    op.drop_index(op.f("ix_claims_verification_status"), table_name="claims")
    op.drop_index(op.f("ix_claims_project_id"), table_name="claims")
    op.drop_index(op.f("ix_claims_paper_version_record_id"), table_name="claims")
    op.drop_index(op.f("ix_claims_importance"), table_name="claims")
    op.drop_index(op.f("ix_claims_claim_type"), table_name="claims")
    op.drop_index(op.f("ix_claims_claim_id"), table_name="claims")
    op.drop_table("claims")
    op.drop_index(op.f("ix_citation_support_checks_status"), table_name="citation_support_checks")
    op.drop_index(
        op.f("ix_citation_support_checks_reviewer_is_mock"), table_name="citation_support_checks"
    )
    op.drop_index(
        op.f("ix_citation_support_checks_reference_id"), table_name="citation_support_checks"
    )
    op.drop_index(
        op.f("ix_citation_support_checks_project_id"), table_name="citation_support_checks"
    )
    op.drop_index(
        op.f("ix_citation_support_checks_paper_version_record_id"),
        table_name="citation_support_checks",
    )
    op.drop_index(op.f("ix_citation_support_checks_claim_id"), table_name="citation_support_checks")
    op.drop_table("citation_support_checks")
    op.drop_index(op.f("ix_paper_versions_verified_result_id"), table_name="paper_versions")
    op.drop_index(op.f("ix_paper_versions_status"), table_name="paper_versions")
    op.drop_index(op.f("ix_paper_versions_project_id"), table_name="paper_versions")
    op.drop_index(op.f("ix_paper_versions_problem_id"), table_name="paper_versions")
    op.drop_index(op.f("ix_paper_versions_paper_id"), table_name="paper_versions")
    op.drop_index(op.f("ix_paper_versions_paper_agent_run_id"), table_name="paper_versions")
    op.drop_index(op.f("ix_paper_versions_manifest_hash"), table_name="paper_versions")
    op.drop_index(op.f("ix_paper_versions_evidence_snapshot_id"), table_name="paper_versions")
    op.drop_index(op.f("ix_paper_versions_evidence_snapshot_hash"), table_name="paper_versions")
    op.drop_table("paper_versions")
    op.drop_index(op.f("ix_literature_references_source_id"), table_name="literature_references")
    op.drop_index(op.f("ix_literature_references_source"), table_name="literature_references")
    op.drop_index(op.f("ix_literature_references_reference_id"), table_name="literature_references")
    op.drop_index(op.f("ix_literature_references_project_id"), table_name="literature_references")
    op.drop_index(
        op.f("ix_literature_references_metadata_status"), table_name="literature_references"
    )
    op.drop_index(op.f("ix_literature_references_doi"), table_name="literature_references")
    op.drop_table("literature_references")
    # ### end Alembic commands ###
