export const provider = {
  provider_id: "deepseek-official",
  display_name: "DeepSeek Official",
  protocol: "openai_chat_completions",
  base_url: "https://api.deepseek.com",
  enabled: true,
  trust_level: "OFFICIAL_VENDOR",
  timeout_seconds: 60,
  connect_timeout_seconds: 10,
  max_response_bytes: 8_388_608,
  verify_tls: true,
  allow_redirects: false,
  additional_headers: {},
  metadata: {},
  health_status: "UNCONFIGURED",
  consecutive_failures: 0,
  cooldown_until: null,
  config_digest: "a".repeat(64),
  created_at: "2026-08-31T00:00:00Z",
  updated_at: "2026-08-31T00:00:00Z",
  credential_configured: false,
};

export const capability = (status = "UNKNOWN", source = "UNKNOWN") => ({
  status,
  source,
  detail: null,
});

export const model = {
  model_id: "deepseek-main",
  provider_id: provider.provider_id,
  display_name: "DeepSeek Main",
  remote_model: "deepseek-v4-flash",
  enabled: true,
  quality_tier: "FLAGSHIP_HIGH",
  quality_tier_source: "USER_DECLARED",
  declared_capabilities: { TEXT: capability("SUPPORTED", "USER_DECLARED") },
  observed_capabilities: {},
  effective_capabilities: {
    TEXT: capability("PARTIAL", "USER_DECLARED"),
    VISION: capability(),
    STRUCTURED_OUTPUT: capability(),
    JSON_MODE: capability(),
    JSON_SCHEMA: capability(),
    TOOLS: capability(),
    STREAMING: capability(),
    REASONING_CONTROL: capability(),
    SYSTEM_ROLE: capability(),
    DEVELOPER_ROLE: capability(),
    LONG_CONTEXT: capability(),
    USAGE_REPORTING: capability(),
  },
  structured_output_strategy: "NATIVE_JSON_SCHEMA",
  tool_calling_strategy: "NO_TOOLS",
  reasoning_mapping: {},
  context_window: null,
  max_output_tokens: null,
  pricing: {},
  trust_level: "OFFICIAL_VENDOR",
  configuration: {},
  config_digest: "b".repeat(64),
  created_at: "2026-08-31T00:00:00Z",
  updated_at: "2026-08-31T00:00:00Z",
};

export const probe = {
  probe_id: "11111111-1111-4111-8111-111111111111",
  provider_id: provider.provider_id,
  model_id: model.model_id,
  provider_config_digest: provider.config_digest,
  model_config_digest: model.config_digest,
  capabilities: {
    TEXT: capability("SUPPORTED", "PROBED"),
    STRUCTURED_OUTPUT: capability("SUPPORTED", "PROBED"),
  },
  authentication_status: "PASS",
  latency_ms: 43,
  usage: { input_tokens: 8, output_tokens: 3, total_tokens: 11 },
  errors: [],
  performed_at: "2026-08-31T01:00:00Z",
  probe_digest: "c".repeat(64),
};
